{
 "title": "GoShimmer Debugging Copy",
 "description": "Shows metrics of a single node.",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(iota_info_app, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MPS, Autopeering, Traffic, Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Message Per Second Per Type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "targets": [
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\"}[1m])) by (instance)",
     "legendFormat": "Message Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\",message_type=\"TransactionType(1337)\"}[1m])) by (instance)",
     "legendFormat": "Transaction Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\",message_type=\"dRNG(111)\"}[1m])) by (instance)",
     "legendFormat": "dRNG Message Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\",message_type=\"faucet(2)\"}[1m])) by (instance)",
     "legendFormat": "Faucet Message Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\",message_type=\"networkdelay(189)\"}[1m])) by (instance)",
     "legendFormat": "Network Delay Message Per Second {{instance}}"
    },
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\",message_type=\"Statement(3)\"}[1m])) by (instance)",
     "legendFormat": "Statements Per Second {{instance}}"
    }
   ]
  },
  {
   "title": "Tips",
   "type": "graph",
   "description": "Shows tips in message and value layer.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_tips_count{instance=~\"$instance\"}",
     "legendFormat": "Tips {{instance}}"
    }
   ]
  },
  {
   "title": "Message Per Second Per Issuer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "MPS" } },
   "targets": [
    {
     "expr": "irate(tangle_own_messages_issued_count{}[5m])",
     "legendFormat": "Message Per Second issued by {{instance}}"
    }
   ]
  },
  {
   "title": "Message Finalization Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(tangle_message_finalization_time{messageType=\"DataMessage\"}[5m]) / irate(tangle_message_finalized_count{messageType=\"DataMessage\"}[5m])",
     "legendFormat": "Msg finalization {$instance}"
    }
   ]
  },
  {
   "title": "Message Per Second Per Instance Booker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "MPS" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tangle_messages_per_component_count{component=\"Booker\",instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "MPS {{instance}} "
    }
   ]
  },
  {
   "title": "Messages in Database",
   "type": "graph",
   "description": "Describes the amount of total, solid and not solid messages in the node's database.",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_solid_count_db{instance=~\"$instance\"}",
     "legendFormat": "Solid Messages in DB {{instance}}"
    },
    {
     "expr": "tangle_message_total_count_db{instance=~\"$instance\"} - tangle_message_solid_count_db{instance=~\"$instance\"}",
     "legendFormat": "Not Solid Messages in DB {{instance}}"
    },
    {
     "expr": "tangle_message_total_count_db{instance=~\"$instance\"}",
     "legendFormat": "Total Messages in DB {{instance}}"
    }
   ]
  },
  {
   "title": "Message Per Second Per Instance",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "MPS" }
   ],
   "targets": [
    {
     "expr": "sum(irate(tangle_messages_per_type_count{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "MPS {{instance}} "
    }
   ]
  },
  {
   "title": "Average Solidification Time",
   "type": "graph",
   "description": "Average time it takes to solidify messages.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "tangle_message_avg_solidification_time{instance=~\"$instance\"}",
     "legendFormat": "Avg Solidification Time {{instance}}"
    }
   ]
  },
  {
   "title": "Missing Messages",
   "type": "graph",
   "description": "Number of messages in missingMessageStore. These are the message the node knows it doesn't have and tries to requests them.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_missing_count_db{instance=~\"$instance\"}",
     "legendFormat": "Missing Messages {{instance}}"
    }
   ]
  },
  {
   "title": "Message Request Queue Size",
   "type": "graph",
   "description": "Number of messages currently requested by the message tangle.",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tangle_message_request_queue_size{instance=~\"$instance\"}",
     "legendFormat": "Message Request Queue Size"
    }
   ]
  }
 ]
}